name: Validate GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    uses: myon-bioinformatics/myon-bioinformatics/.github/workflows/reusable-actionlint.yml@main
